app/jobs/regular/process_alert.rb
app/jobs/regular/process_grouped_alerts.rb
plugin.rb
spec/integration/discourse_prometheus_alert_receiver/receiver_controller_spec.rb

`topic.custom_fields[klass::TOPIC_TITLE_CUSTOM_FIELD]` contains the generated title, including `(N firing)`. Instead of reusing that one, this PR uses `generate_title` to regenerate the title.

FIX: Resync topic titles.

---

app/jobs/regular/process_alert.rb
app/jobs/regular/process_grouped_alerts.rb

Zeitwerk is failing when we are searching for Jobs::Onceoff and Jobs::Base without going back to the top-level namespace (this is correlated to the fact that we got Onceoff base class and module with the same name). 
I noticed that in plugins we are using sometimes :: and sometimes not and that gives me comfort that this change will not break anything.
Travis error: https://travis-ci.org/discourse/discourse/jobs/585072364

FIX: Use top-level namespace for base classes

---

app/jobs/concerns/alert_post_mixin.rb
app/jobs/regular/process_alert.rb
app/jobs/regular/process_grouped_alerts.rb
assets/javascripts/discourse/initializers/initialize-discourse-prometheus-alert-receiver.js.es6
assets/javascripts/discourse/widgets/alert-receiver.js.es6
assets/stylesheets/topic-post.scss
config/locales/client.en.yml
config/locales/server.en.yml
plugin.rb
spec/integration/discourse_prometheus_alert_receiver/receiver_controller_spec.rb
test/javascripts/acceptance/alert-receiver-test.js.es6

This commit changes from rendering alerts in post markdown to rendering them directly in the JS app. This means that updating the database with incoming alert data is much cheaper, and also gives us the flexibility to improve the alert UI in future without being restricted by markdown.

REFACTOR: Move rendering to client-side

---

app/controllers/discourse_prometheus_alert_receiver/receiver_controller.rb
app/jobs/concerns/alert_post_mixin.rb
app/jobs/regular/process_alert.rb
app/jobs/regular/process_grouped_alerts.rb
app/models/alert_receiver_alert.rb
app/serializers/alert_receiver_alert.rb
assets/javascripts/discourse/widgets/alert-receiver.js.es6
db/migrate/20200806144401_create_alert_receiver_alerts.rb
plugin.rb
spec/integration/discourse_prometheus_alert_receiver/receiver_controller_spec.rb
spec/lib/topic_query_spec.rb
spec/model/alert_receiver_alert_spec.rb
spec/serializers/site_serializer_spec.rb
test/javascripts/acceptance/alert-receiver-test.js.es6

This provides a few important benefits over JSON blobs:
- Alert data has a fixed schema
- We can query it more efficiently
- We can update it using upsert queries
A migration is included for currently open alert topics. Closed topics will only be migrated if they are using client-side rendering.

REFACTOR: Use a dedicated table for storing alert data

---

app/jobs/concerns/alert_post_mixin.rb
app/jobs/regular/process_alert.rb
spec/integration/discourse_prometheus_alert_receiver/receiver_controller_spec.rb

topic_tags is an optional, comma separated, list of Discourse tags which will be added to the alert topic

FEATURE: Introduce support for topic_tags annotation

---

plugin.rb

`alert_data.present?` is always true, because it's an instance of `ActiveModel::ArraySerializer`

FIX: Only include alert_data in topic_view when it exists

---

app/jobs/regular/create_alert_topics_index.rb
db/migrate/20210608034155_add_alert_topics_index.rb
plugin.rb
spec/model/topic_spec.rb

Instead of scanning all the opened topics like the previous query did,
we only scan for topics inside the configured alert categories. A
partial index is also used here so that we don't have to index other
topics unnecessarily.
On one of our own internal instance, this reduces the time spent on this
query from ~20ms to ~4ms.

PERF: Add partial index for alert topics.

---

plugin.rb
spec/serializers/site_serializer_spec.rb

A per process cache does not really work well when ActiveRecord
callbacks are only executed on a single process.
Follow-up to ce5e52ba317381fa516da1a08ea095940224457c

FIX: Switch alerts category ids cache to distributed cache.

---

app/controllers/discourse_prometheus_alert_receiver/receiver_controller.rb
spec/integration/discourse_prometheus_alert_receiver/receiver_controller_spec.rb

The `ProcessAlert` job expects the receiver to always have a topic_map, regardless of whether or not an assignee_group was included when the receiver was initially created.

FIX: `topic_map` should always be present

---

app/jobs/concerns/alert_post_mixin.rb
app/jobs/regular/process_alert.rb
spec/integration/discourse_prometheus_alert_receiver/receiver_controller_spec.rb

If needed, this functionality can be replicated using the more generic `discourse_tags` labels

Remove 'priority' system

---

app/jobs/concerns/alert_post_mixin.rb
plugin.rb
spec/model/topic_spec.rb

In production, we are running the following query:
`SELECT COUNT(*) FROM topics INNER JOIN alert_receiver_alerts arr ON arr.topic_id = topics.id WHERE deleted_at IS NULL AND NOT topics.closed AND topics.category_id IN (1);`
When we run `EXPLAIN ANALYZE`, the above query results uses a merge join
which joins the topics table against the entire `alert_receiver_alerts` table.
As the `alert_receiver_alerts` table grows, this query becomes more
inefficient.
Instead, this commit uses two queries. One to fetch the
open topic ids from the alert category and another query to check if
those topic ids contain alerts. Both query is highly optimized with
indexes.
On our production instance with about 120K alerts, this reduces the query time to count open
alert topics from ~20ms to about ~2ms.
Also …

PERF: Improve performance of counting open alert topics.

---

assets/stylesheets/topic-post.scss

FIX: Prevent time tip pop-up from being hidden

---

app/jobs/regular/create_alert_topics_index.rb

Error in production which we saw:
```
Message (4 copies reported)
Job exception: ERROR:  canceling statement due to lock timeout
Backtrace
rack-mini-profiler-3.0.0/lib/patches/db/pg.rb:110:in `exec'
rack-mini-profiler-3.0.0/lib/patches/db/pg.rb:110:in `async_exec'
(eval):29:in `async_exec'
mini_sql-1.4.0/lib/mini_sql/postgres/connection.rb:209:in `run'
mini_sql-1.4.0/lib/mini_sql/active_record_postgres/connection.rb:38:in `block in run'
mini_sql-1.4.0/lib/mini_sql/active_record_postgres/connection.rb:34:in `block in with_lock'
activesupport-7.0.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
activesupport-7.0.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize' …
```

FIX: Drop index concurrently so that it doesn't lock up the table

---

assets/javascripts/discourse/components/alert-receiver/date-range.hbs
assets/javascripts/discourse/components/alert-receiver/timestamp.hbs
assets/stylesheets/topic-post.scss

- Scroll table horizontally instead of overflowing
- Make timestamp ranges wrap to two lines instead of three
Before:
After:

UX: Improve behaviour on small-width screens

---

assets/javascripts/discourse/components/alert-receiver/timestamp.hbs

This regressed in the widget -> glimmer conversion in 5d27f4d26e35e09ba5e58288b61b4ae54797b652

FIX: Display timestamps as UTC

---

assets/stylesheets/topic-post.scss

978e802ecb83c8397c3e0ae0d2c30173fefee381 introduced `overflow: hidden` on `.alert-table-wrapper`. That caused the local-dates popover to be clipped when it escaped the wrapper.
`position: fixed` elements like the local-dates popover are positioned based on their closest `position: relative` element. Previously, it was the `<table>` itself, which is inside the `overflow: hidden` wrapper. This commit removes that, so that the nearest `position: relative` parent is **outside** the `overflow: hidden` element, thereby avoiding the clipping.
Before:
After:

UX: Ensure local-dates popover is not clipped

---

app/jobs/concerns/alert_post_mixin.rb

We have replaced the `#pluck_first` freedom patch with the native `#pick` in core [here](https://github.com/discourse/discourse/pull/19893).
This change is updates this plugin in the same fashion.

DEV: Replace #pluck_first monkey patch with native #pick

---

spec/integration/discourse_prometheus_alert_receiver/receiver_controller_spec.rb

The `#queue_jobs=` method on site settings has been [deprecated](https://github.com/discourse/discourse/commit/1b65469b64e9e569fed67ae11f1dd9ee37702f5c) and replaced by `Jobs.run_later!` and `Jobs.run_immediately!`. This PR replaces usages in this plugin so we can remove the fallback in core.
The fallback used in core for reference:
https://github.com/discourse/discourse/blob/main/app/models/site_setting.rb#L109-L115

DEV: Replace deprecated queue_jobs site setting in tests

---

spec/integration/discourse_prometheus_alert_receiver/notification_overrides_spec.rb

We're updating a bunch of site settings that restrict access to use groups instead of TL. This requires certain specs to ensure that auto-groups are fabricated in order to work.

DEV: Update tests to work with new group access

---

README.md
app/jobs/regular/process_alert.rb
spec/integration/discourse_prometheus_alert_receiver/receiver_controller_spec.rb

This commit changes two main things:
1. `topic_assignee` will only accept `User#username` now. Having to
support both `User#username` and `User#id` complicates the code too
much.
2. Rename `group_topic_assignee` to `topic_group_assignee` which will
accept `Group#name`. When the annotation is present, the topic will
automatically be assigned to the specified group`

FEATURE: Update `topic_assignee` and `topic_group_assignee` annotations
